version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-staging_password}
    volumes:
      - /opt/invoicing-staging/postgres:/var/lib/postgresql/data
    restart: always

  backend:
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:staging_password@postgres:5432/invoicing?sslmode=disable}
      - JWT_SECRET=${JWT_SECRET:-staging_jwt_secret_key}
      - PORT=8080
      - GIN_MODE=release
    restart: always
    ports:
      - "8081:8080"  # Different port for staging

  # Optional: Add a simple nginx for staging
  nginx:
    image: nginx:alpine
    container_name: invoicing-staging-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: always
